import { Inter } from "next/font/google";
import "../components/style/style.css";
import Navbar from "@/components/shared/navbar";
import Footer from "@/components/shared/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=''>
      <Navbar/>

        {children}
        
        <Footer></Footer>
        </body>
      
    </html>
  );
}
